In [1]:
import torch
import numpy as np
from torch import nn
from torchvision.ops import roi_align

In [2]:
A = np.arange(7*7, dtype=np.float32).reshape((1, 1, 7, 7))
A = torch.Tensor(A)

In [3]:
A.shape

torch.Size([1, 1, 7, 7])

In [24]:
B = torch.Tensor(np.array([[-1, -1, 1, 1]], dtype=np.float32))
B = B * 1.5 + 3.0
B

tensor([[1.5000, 1.5000, 4.5000, 4.5000]])

In [25]:
output = roi_align(A, [B], (3, 3), 1, 1)

In [26]:
output.shape

torch.Size([1, 1, 3, 3])

In [27]:
output

tensor([[[[16., 17., 18.],
          [23., 24., 25.],
          [30., 31., 32.]]]])

In [13]:
A

tensor([[[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
          [ 7.,  8.,  9., 10., 11., 12., 13.],
          [14., 15., 16., 17., 18., 19., 20.],
          [21., 22., 23., 24., 25., 26., 27.],
          [28., 29., 30., 31., 32., 33., 34.],
          [35., 36., 37., 38., 39., 40., 41.],
          [42., 43., 44., 45., 46., 47., 48.]]]])